services:
  backend:
    image: monitor-backend:v1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - nodes_config
    deploy:
      replicas: ${BACKEND_REPLICAS:-1}
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        service: monitor-backend
    networks:
      - monitor-network

  frontend:
    image: monitor-frontend:v1
    ports:
      - "8081:80"
    deploy:
      replicas: ${FRONTEND_REPLICAS:-1}
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        service: monitor-frontend
    networks:
      - monitor-network
networks:
  monitor-network:
    driver: overlay

secrets:
  nodes_config:
    external: true
  
    